// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $latest_n_ from "./routes/latest/[[n]].tsx";
import * as $Chart from "./islands/Chart.tsx";
import * as $Hide from "./islands/Hide.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/latest/[[n]].tsx": $latest_n_,
  },
  islands: {
    "./islands/Chart.tsx": $Chart,
    "./islands/Hide.tsx": $Hide,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
